#site settings
title: Great New Blog Title
author:
 name: Josiah Marquez
 email: your-email@domain.com
description: "Greate site about Jekyll on GH-Pages."
 
#build settings
remote_theme: jekyll/minima
